# Generated by Django 5.1.5 on 2025-03-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_alter_custommessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommessage',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
