# Generated by Django 5.1.5 on 2025-02-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_alter_custommessage_user'),
        ('profiles', '0002_alter_user_email_address_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
