# Generated by Django 5.1.5 on 2026-08-16 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpreference',
            name='stock_preference_four',
        ),
        migrations.RemoveField(
            model_name='stockpreference',
            name='stock_preference_one',
        ),
        migrations.RemoveField(
            model_name='stockpreference',
            name='stock_preference_three',
        ),
        migrations.RemoveField(
            model_name='stockpreference',
            name='stock_preference_two',
        ),
        migrations.AddField(
            model_name='stockpreference',
            name='symbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='stockpreference',
            constraint=models.UniqueConstraint(fields=('user', 'symbol'), name='unique_user_stock_symbol'),
        ),
    ]
