# Generated by Django 5.1.5 on 2026-08-17 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0002_remove_stockpreference_stock_preference_four_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=10)),
                ('triggered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
