# Generated by Django 5.1.5 on 2026-08-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0003_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
